### ISSUE TITLE
Possible to add same tag

### ISSUE THREAD

**Issue by kouKatsumi** [sheepsy90/django-rbe#17]
It's possible to add same tag few times. Probably should be validated.

Attachment: tag "java" added twice.
![screen shot 2016-10-17 at 12 39 43](https://cloud.githubusercontent.com/assets/10888481/19513735/4a726dfc-95f1-11e6-8d21-ec07a9dd728f.png)

**Comment by sheepsy90** [comment]
This will be fixed with #22 as it changes in structure anyway.
