### ISSUE TITLE
Chat entry field too small & non-navigable

### ISSUE THREAD

**Issue by GalacticPrez** [sheepsy90/django-rbe#38]
When you enter long text into a chat (or other) entry field, the text is difficult to edit if the field is non-navigable ... ie - your text goes outside the visible bounds of the entry field, and you cannot get the cursor to other non-visible parts of the text in order to remove, insert new, or edit existing text ... this is a problem as it is severely limiting on conversations, which is the entire point of using the platform.

Secondly (and related), when looking at your "close contacts" (might I suggest a better phrasing would be "nearby contacts"), there's no way from a mobile to tap & hold the names in order to have the link open in a new tab, which is also limiting on conversations, as it means I have to keep going back in the browser, or otherwise re-navigating to my profile instead of just closing the tab after finishing each conversation to thus return to the profile tab & start the next conversation in the same way, by selecting a contact, pressing & holding the link to get a new tab.

**Comment by sheepsy90** [comment]
Good points - do you think the nearby people is prominent enough?

**Comment by GalacticPrez** [comment]
Well I think clearly the whole thing is a work in progress, you can always improve things, but perhaps what might work better if you want prominence is a major link in the top navigation bar saying "My Network", and then under that you have "Contacts" (for people you want to short list as interesting to you), and then "Nearby" to find people either within proximity to your default location OR to find people nearby to another specified location ... then keep building on those network tools/options over time.

But you can only do what you've got time to do ... so I wouldn't worry too much about that just yet if there's other greater priorities.

**Comment by sheepsy90** [comment]
I added some small things and adjustments you mentioned - can you create specific tickets for the distance / friends option. It's easier for the backlog then.
